// AUTO-GENERATED by scripts/generate-extension-videos.mjs
// Do not edit manually — run: node scripts/generate-extension-videos.mjs
// Last generated: 2026-03-09T06:41:54.703Z

const ILLIT_VIDEOS = [
  {
    "id": "magnetic-mv",
    "youtubeId": "Vk5-c_v4gMU",
    "title": "ILLIT - Magnetic (MV)",
    "duration": 180
  },
  {
    "id": "lucky-girl-syndrome",
    "youtubeId": "UCmgGZbfjmk",
    "title": "ILLIT - Lucky Girl Syndrome (MV)",
    "duration": 164
  },
  {
    "id": "cherish-mv",
    "youtubeId": "tbDGl7jEazA",
    "title": "ILLIT - Cherish (My Love) (MV)",
    "duration": 179
  },
  {
    "id": "tick-tack-mv",
    "youtubeId": "-nEGVrzPaiU",
    "title": "ILLIT - Tick-Tack (MV)",
    "duration": 182
  },
  {
    "id": "little-monster",
    "youtubeId": "xRU1XXHIpIc",
    "title": "ILLIT - little monster (MV)",
    "duration": 147
  },
  {
    "id": "do-the-dance",
    "youtubeId": "negtrQu5mTA",
    "title": "ILLIT - Do the Dance (MV)",
    "duration": 174
  },
  {
    "id": "jellyous",
    "youtubeId": "GkG60kISnfc",
    "title": "ILLIT - Jellyous (MV)",
    "duration": 153
  },
  {
    "id": "toki-yo-tomare",
    "youtubeId": "HeqsjDF7Lw0",
    "title": "ILLIT - Toki Yo Tomare (MV)",
    "duration": 170
  },
  {
    "id": "almond-chocolate-mv",
    "youtubeId": "qlgEadao-Sk",
    "title": "ILLIT - Almond Chocolate (MV)",
    "duration": 226
  },
  {
    "id": "not-cute-anymore",
    "youtubeId": "x_RYZsOfpKY",
    "title": "ILLIT - NOT CUTE ANYMORE (MV)",
    "duration": 161
  },
  {
    "id": "sunday-morning",
    "youtubeId": "-01oDwXKSuE",
    "title": "ILLIT - Sunday Morning (MV)",
    "duration": 168
  },
  {
    "id": "not-me",
    "youtubeId": "9nEp9eeGaJk",
    "title": "ILLIT - NOT ME (MV)",
    "duration": 156
  },
  {
    "id": "aim-high",
    "youtubeId": "4p3Yy-HiMUE",
    "title": "ILLIT - Aim High",
    "duration": 180
  },
  {
    "id": "-illit-magnetic-4k-illit-ill-show-it-mnet-240325",
    "youtubeId": "TEKyEQL-S8o",
    "title": "[최초공개] ILLIT(아일릿) - Magnetic (4K) | ILLIT : I\\",
    "duration": 198
  },
  {
    "id": "-illit-my-world-4k-illit-ill-show-it-mnet-240325",
    "youtubeId": "K8FskDXVzGM",
    "title": "[최초공개] ILLIT(아일릿) - My World (4K) | ILLIT : I\\",
    "duration": 125
  },
  {
    "id": "-illit-lucky-girl-syndrome-4k-illit-ill-show-it-mnet-240325",
    "youtubeId": "S9a3jPQVqAE",
    "title": "[최초공개] ILLIT(아일릿) - Lucky Girl Syndrome (4K) | ILLIT : I\\",
    "duration": 196
  },
  {
    "id": "-illit-midnight-fiction-4k-illit-ill-show-it-mnet-240325",
    "youtubeId": "ME7nQsZF53Y",
    "title": "[최초공개] ILLIT(아일릿) - Midnight Fiction (4K) | ILLIT : I\\",
    "duration": 182
  },
  {
    "id": "-l-4k-illit-magnetic-l-ep656",
    "youtubeId": "2hZAtIEJV0E",
    "title": "[주간아 짐벌캠 l 4K] ILLIT (아일릿) -  Magnetic l EP.656",
    "duration": 171
  },
  {
    "id": "hot-debut-illit-my-world-ep835-mnet-240328",
    "youtubeId": "nTP_b0_dDzg",
    "title": "\\",
    "duration": 122
  },
  {
    "id": "hot-debut-illit-magnetic-ep835-mnet-240328",
    "youtubeId": "O69XRGnuUEM",
    "title": "\\",
    "duration": 222
  },
  {
    "id": "magnetic-illit-music-bank-kbs-world-tv-240329",
    "youtubeId": "nXzD9vXtscs",
    "title": "Magnetic - ILLIT [Music Bank] | KBS WORLD TV 240329",
    "duration": 172
  },
  {
    "id": "my-world-illit-music-bank-kbs-world-tv-240329",
    "youtubeId": "QB45SV5nnSQ",
    "title": "My World - ILLIT [Music Bank] | KBS WORLD TV 240329",
    "duration": 115
  },
  {
    "id": "illit-magnetic-show-musiccore-mbc240330",
    "youtubeId": "2RFQ7g13PoU",
    "title": "ILLIT (아일릿) - Magnetic | Show! MusicCore | MBC240330방송",
    "duration": 171
  },
  {
    "id": "illit-my-world-show-musiccore-mbc240330",
    "youtubeId": "g8qVJ_AA3jM",
    "title": "ILLIT (아일릿) - My World | Show! MusicCore | MBC240330방송",
    "duration": 111
  },
  {
    "id": "illit-magnetic-inkigayo-20240331",
    "youtubeId": "YGayuTY4CUg",
    "title": "ILLIT (아일릿) - Magnetic @인기가요 inkigayo 20240331",
    "duration": 187
  },
  {
    "id": "illit-my-world-inkigayo-20240331",
    "youtubeId": "VZS7I0zQD7c",
    "title": "ILLIT (아일릿) - My World @인기가요 inkigayo 20240331",
    "duration": 119
  },
  {
    "id": "illit-magnetic-magnetic-the-show-240402",
    "youtubeId": "ynkH4Bwa6_M",
    "title": "ILLIT, Magnetic (아일���, Magnetic) [THE SHOW 240402]",
    "duration": 189
  },
  {
    "id": "illit-my-world-my-world-the-show-240402",
    "youtubeId": "szNH7Zs93rc",
    "title": "ILLIT, My World (아일릿, My World) [THE SHOW 240402]",
    "duration": 115
  },
  {
    "id": "hot-debut-illit-magnetic-l-show-champion-l-ep512-l-240403",
    "youtubeId": "vt-_JXEXN6o",
    "title": "[HOT DEBUT] 아일릿(ILLIT) - Magnetic l Show Champion l EP.512 l 240403",
    "duration": 182
  },
  {
    "id": "illit-my-world-l-show-champion-l-ep512-l-240403",
    "youtubeId": "_GmY8-MzNC8",
    "title": "아일릿(ILLIT) - My World l Show Champion l EP.512 l 240403",
    "duration": 107
  },
  {
    "id": "illit-magnetic-ep836-mnet-240404",
    "youtubeId": "ybgN5qmzhOw",
    "title": "아일릿(ILLIT) - Magnetic #엠카운트다운 EP.836 | Mnet 240404 방송",
    "duration": 172
  },
  {
    "id": "magnetic-illit-music-bank-kbs-world-tv-240405",
    "youtubeId": "fUtT_Fja0YM",
    "title": "Magnetic - ILLIT (아일릿) [Music Bank] | KBS WORLD TV 240405",
    "duration": 183
  },
  {
    "id": "illit-magnetic-show-musiccore-mbc240406",
    "youtubeId": "CbqqSpfrVKg",
    "title": "ILLIT (아일릿) - Magnetic | Show! MusicCore | MBC240406방송",
    "duration": 168
  },
  {
    "id": "illit-magnetic-inkigayo-20240407",
    "youtubeId": "YtHAC120Zw4",
    "title": "ILLIT (아일릿) - Magnetic @인기가요 inkigayo 20240407",
    "duration": 180
  },
  {
    "id": "illit-magnetic-magnetic-the-show-240409",
    "youtubeId": "jdCphm4LMEg",
    "title": "ILLIT, Magnetic (아일릿, Magnetic) [THE SHOW 240409]",
    "duration": 174
  },
  {
    "id": "illit-magnetic-l-show-champion-l-ep513-l-240410",
    "youtubeId": "yoWcnuTSwjw",
    "title": "아일릿(ILLIT) - Magnetic l Show Champion l EP.513 l 240410",
    "duration": 167
  },
  {
    "id": "illit-magnetic-ep837-mnet-240411",
    "youtubeId": "fD8Yj4kNh50",
    "title": "아일릿(ILLIT) - Magnetic #엠카운트다운 EP.837 | Mnet 240411 방송",
    "duration": 170
  },
  {
    "id": "simply-k-pop-con-tour-illit-my-world-magnetic-_simplys-spotl",
    "youtubeId": "mMgC5qoE_s4",
    "title": "[Simply K-Pop CON-TOUR] ILLIT(아일릿) - \\",
    "duration": 364
  },
  {
    "id": "magnetic-illit-music-bank-kbs-world-tv-240412",
    "youtubeId": "v0QLje6xYgA",
    "title": "Magnetic - ILLIT (아일릿) [Music Bank] | KBS WORLD TV 240412",
    "duration": 182
  },
  {
    "id": "illit-magnetic-show-musiccore-mbc240413",
    "youtubeId": "XUWySVhVY44",
    "title": "ILLIT (아일릿) - Magnetic | Show! MusicCore | MBC240413방송",
    "duration": 168
  },
  {
    "id": "illit-magnetic-inkigayo-20240414",
    "youtubeId": "Ot1LBMNai_Y",
    "title": "ILLIT (아일릿) - Magnetic @인기가요 inkigayo 20240414",
    "duration": 179
  },
  {
    "id": "illit-lucky-girl-syndrome-ep838-mnet-240418",
    "youtubeId": "LIVJnfDjKhM",
    "title": "아일릿(ILLIT) - Lucky Girl Syndrome #엠카운트다운 EP.838 | Mnet 240418 방송",
    "duration": 156
  },
  {
    "id": "illit-lucky-girl-syndrome-show-musiccore-mbc240420",
    "youtubeId": "fYltZ7dJ11U",
    "title": "ILLIT (아일릿) - Lucky Girl Syndrome | Show! MusicCore | MBC240420방송",
    "duration": 143
  },
  {
    "id": "illit-lucky-girl-syndrome-inkigayo-20240421",
    "youtubeId": "mZbup-jNns0",
    "title": "ILLIT (아일릿) - Lucky Girl Syndrome @인기가요 inkigayo 20240421",
    "duration": 162
  },
  {
    "id": "illit-lucky-girl-syndrome-lucky-girl-syndrome-the-show-24042",
    "youtubeId": "CPOmORBww9Y",
    "title": "ILLIT, Lucky Girl Syndrome (아일릿, Lucky Girl Syndrome) [THE SHOW 240423]",
    "duration": 161
  },
  {
    "id": "illit-lucky-girl-syndrome-l-show-champion-l-ep515-l-240424",
    "youtubeId": "8gLXfGFVoR0",
    "title": "아일릿(ILLIT) - Lucky Girl Syndrome l Show Champion l EP.515 l 240424",
    "duration": 149
  },
  {
    "id": "lucky-girl-syndrome-illit-music-bank-kbs-world-tv-240426",
    "youtubeId": "dcWjn0awVhc",
    "title": "Lucky Girl Syndrome - ILLIT アイリット 아일릿 [Music Bank] | KBS WORLD TV 240426",
    "duration": 166
  },
  {
    "id": "-illit-magnetic-lucky-girl-syndrome-kbs-240428",
    "youtubeId": "6RZrPUGN-lc",
    "title": "[#열린음악회] 아일릿(ILLIT) - Magnetic, Lucky Girl Syndrome | KBS 240428 방송",
    "duration": 299
  },
  {
    "id": "-girls-award-2024-illit-live-in-japan-20240503",
    "youtubeId": "Mb1qfiPQ47o",
    "title": "ガールズアワード Girls Award 2024 ILLIT 아일릿 アイリ���ト LIVE in JAPAN 2024.05.03",
    "duration": 721
  },
  {
    "id": "240509-illit-magnetic-4k-60p-by-dafttaengk",
    "youtubeId": "aS3x0nnr1JE",
    "title": "240509 첫 대학축제! 아일릿 ILLIT \\",
    "duration": 168
  },
  {
    "id": "4k-illit-magnetic-240521-kutopia-1",
    "youtubeId": "XSEJykhtLXg",
    "title": "[4K] 고려대학교 축제 아일릿 (ILLIT) MAGNETIC | 240521 석탑대동제 KUTOPIA 1일차",
    "duration": 169
  },
  {
    "id": "illit-intromagnetic-inkigayo-20240609",
    "youtubeId": "0cMBBfegLZ0",
    "title": "ILLIT (아일릿) - INTRO+Magnetic @인기가요 inkigayo 20240609",
    "duration": 212
  },
  {
    "id": "-illit-240525-139-live-cam",
    "youtubeId": "3SUDiSLFq_0",
    "title": "아카라카를 온누리에 아일릿 (ILLIT)ㅣ 240525 개교 139주년 아카라카를 온누리에 Live Cam",
    "duration": 959
  },
  {
    "id": "illitmagnetic",
    "youtubeId": "bRr82uDVb4A",
    "title": "【ILLIT】世界中で大バズり中！「Magnetic」生パフォーマンス！",
    "duration": 158
  },
  {
    "id": "illit-magnetic-stage-cam-aliexpress-2024-weverse-con-festiva",
    "youtubeId": "Or8A-P5A8I0",
    "title": "ILLIT(아일릿) \\",
    "duration": 206
  },
  {
    "id": "illit-magnetic-in-japan-mbc240717",
    "youtubeId": "DaWukrUb8po",
    "title": "ILLIT (아일릿) - Magnetic | 쇼! 음악중심 in JAPAN | MBC240717방송",
    "duration": 162
  },
  {
    "id": "illit-lucky-girl-syndrome-in-japan-mbc240717",
    "youtubeId": "_6RFhxv1Ttg",
    "title": "ILLIT (아일릿) - Lucky Girl Syndrome | 쇼! 음악중심 in JAPAN | MBC240717방송",
    "duration": 143
  },
  {
    "id": "illit-lucky-girl-syndrome-magnetic-festival-ver-gayodaejeon",
    "youtubeId": "UmYssEnbmvE",
    "title": "ILLIT (아일릿) - Lucky Girl Syndrome + Magnetic (Festival ver.) @가요대전 썸머 GayoDaejeon Summer 20240726",
    "duration": 252
  },
  {
    "id": "illit-magnetic-show-musiccore-mbc240817",
    "youtubeId": "5khgtzH-J1Q",
    "title": "ILLIT (아일릿) - Magnetic | Show! MusicCore | MBC240817방송",
    "duration": 162
  },
  {
    "id": "-illit-iykyk-if-you-know-you-know-ep868-mnet-241024",
    "youtubeId": "ncr9FdM0fLs",
    "title": "\\",
    "duration": 173
  },
  {
    "id": "-illit-cherish-my-love-ep868-mnet-241024",
    "youtubeId": "sQEU4FDs96Y",
    "title": "\\",
    "duration": 244
  },
  {
    "id": "iykyk-illit-music-bank-kbs-world-tv-241025",
    "youtubeId": "NuvbIlJhYyM",
    "title": "IYKYK - ILLIT アイリット 아일릿 [Music Bank] | KBS WORLD TV 241025",
    "duration": 181
  },
  {
    "id": "cherish-my-love-illit-music-bank-kbs-world-tv-241025",
    "youtubeId": "7oFT3hh8h_g",
    "title": "Cherish (My Love) - ILLIT アイリット 아일릿 [Music Bank] | KBS WORLD TV 241025",
    "duration": 186
  },
  {
    "id": "-cherish-illit-cherish-my-love",
    "youtubeId": "8r29EKYaO2w",
    "title": "[잠옷직캠] 아일릿이 잠옷입고 읏쇼읏쇼 추는 Cherish 본다 만다 | 돌들의침묵 | 아일릿(ILLIT) \\",
    "duration": 187
  },
  {
    "id": "-illit-cherish-my-love-ver",
    "youtubeId": "orTpgUtQEyw",
    "title": "[오지구영] ILLIT (아일릿) - Cherish (My Love) (오지는 캠ver.)",
    "duration": 194
  },
  {
    "id": "illit-iykyk-if-you-know-you-know-show-musiccore-mbc241026",
    "youtubeId": "79LkULO7vic",
    "title": "ILLIT (아일릿) - IYKYK (If You Know You Know) | Show! MusicCore | MBC241026방송",
    "duration": 150
  },
  {
    "id": "illit-cherish-my-love-show-musiccore-mbc241026",
    "youtubeId": "KpenEfkLs_8",
    "title": "ILLIT (아일릿) - Cherish (My Love) | Show! MusicCore | MBC241026방송",
    "duration": 187
  },
  {
    "id": "illit-iykyk-if-you-know-you-know-inkigayo-20241027",
    "youtubeId": "0gLqyScO248",
    "title": "ILLIT (아일릿) - IYKYK (If You Know You Know) @인기가요 inkigayo 20241027",
    "duration": 167
  },
  {
    "id": "illit-cherish-my-love-inkigayo-20241027",
    "youtubeId": "o69y6-KvkMU",
    "title": "ILLIT (아일릿) - Cherish (My Love) @인기가요 inkigayo 20241027",
    "duration": 214
  },
  {
    "id": "-l-4k-illit-cherish-my-love-l-ep687",
    "youtubeId": "-nurtM1Wtcc",
    "title": "[주간아 짐벌캠 l 4K] ILLIT (아일릿) -  Cherish (My Love) l EP.687",
    "duration": 187
  },
  {
    "id": "kcon-germany-2024-illit-magneticdream-stage-mnet-241031",
    "youtubeId": "k8zAykrCgJg",
    "title": "[KCON GERMANY 2024] ILLIT (아일릿) - Magnetic@DREAM STAGE | Mnet 241031 방송",
    "duration": 177
  },
  {
    "id": "241031-illit-lucky-girl-syndrome-mnet-kcon-germany-2024-x-m",
    "youtubeId": "MMpWzwlRJBU",
    "title": "241031 아일릿(ILLIT) - Lucky Girl Syndrome @ Mnet KCON GERMANY 2024 X M COUNTDOWN",
    "duration": 164
  },
  {
    "id": "cherish-my-love-illit-music-bank-kbs-world-tv-241101",
    "youtubeId": "B1XBIPm11c8",
    "title": "Cherish (My Love) - ILLIT アイリット 아일릿 [Music Bank] | KBS WORLD TV 241101",
    "duration": 204
  },
  {
    "id": "illit-cherish-my-love-show-musiccore-mbc241102",
    "youtubeId": "AC0KliUFM2c",
    "title": "ILLIT (아일릿) - Cherish (My Love) | Show! MusicCore | MBC241102방송",
    "duration": 194
  },
  {
    "id": "illit-cherish-my-love-inkigayo-20241103",
    "youtubeId": "7wiqynZB8jo",
    "title": "ILLIT (아일릿) - Cherish (My Love) @인기가요 inkigayo 20241103",
    "duration": 204
  },
  {
    "id": "cherish-my-love-illit-music-bank-kbs-world-tv-241108",
    "youtubeId": "RZgJt-clKm0",
    "title": "Cherish (My Love) - ILLIT アイリット 아일릿 [Music Bank] | KBS WORLD TV 241108",
    "duration": 185
  },
  {
    "id": "illit-cherish-my-love-show-musiccore-mbc241109",
    "youtubeId": "3uC6CHVDMWk",
    "title": "ILLIT (아일릿) - Cherish (My Love) | Show! MusicCore | MBC241109방송",
    "duration": 185
  },
  {
    "id": "illit-cherish-my-love-inkigayo-20241110",
    "youtubeId": "JbYFzxYbRAY",
    "title": "ILLIT (아일릿) - Cherish (My Love) @인기가요 inkigayo 20241110",
    "duration": 202
  },
  {
    "id": "tick-tack-illit-music-bank-kbs-world-tv-241115",
    "youtubeId": "KZumKIrILA4",
    "title": "Tick-Tack - ILLIT アイリット 아일릿 [Music Bank] | KBS WORLD TV 241115",
    "duration": 132
  },
  {
    "id": "illit-tick-tack-show-musiccore-mbc241116",
    "youtubeId": "UWzObn7_F7Y",
    "title": "ILLIT (아일릿) - Tick-Tack | Show! MusicCore | MBC241116방송",
    "duration": 138
  },
  {
    "id": "illit-tick-tack-inkigayo-20241117",
    "youtubeId": "MffbliVhUgg",
    "title": "ILLIT (아일릿) - Tick-Tack @인기가요 inkigayo 20241117",
    "duration": 150
  },
  {
    "id": "2024mama-illit-magnetic-cherish-my-love-mnet-241122",
    "youtubeId": "IiMSmriHe4I",
    "title": "[#2024MAMA] 아일릿(ILLIT) - Magnetic + Cherish (My Love) | Mnet 241122 방송",
    "duration": 611
  },
  {
    "id": "2024mama-illit-heart-shaker-twice-mnet-241122",
    "youtubeId": "OsDsyOtFtX4",
    "title": "[#2024MAMA] 아일릿(ILLIT) - Heart Shaker (원곡：TWICE(트와이스)) | Mnet 241122 방송",
    "duration": 135
  },
  {
    "id": "tick-tack-illit-music-bank-kbs-world-tv-241122",
    "youtubeId": "x1aK8dWdP88",
    "title": "Tick-Tack - ILLIT アイリット 아일릿 [Music Bank] | KBS WORLD TV 241122",
    "duration": 141
  },
  {
    "id": "illit-tick-tack-show-musiccore-mbc241123",
    "youtubeId": "akD_gU3kUcQ",
    "title": "ILLIT (아일릿) - Tick-Tack | Show! MusicCore | MBC241123방송",
    "duration": 140
  },
  {
    "id": "illit-tick-tack-inkigayo-20241124",
    "youtubeId": "29FjJKIc6Kg",
    "title": "ILLIT (아일릿) - Tick-Tack @인기가요 inkigayo 20241124",
    "duration": 151
  },
  {
    "id": "illit-tick-tack-inkigayo-20241201",
    "youtubeId": "eF2dpcWoZJM",
    "title": "ILLIT (아일릿) - Tick-Tack @인기가요 inkigayo 20241201",
    "duration": 152
  },
  {
    "id": "tick-tack-illit-2024-music-bank-gfj-kbs-world-tv-241219",
    "youtubeId": "T3dkFipteos",
    "title": "Tick-Tack - ILLIT 아일릿 [2024 MUSIC BANK GFJ]  KBS WORLD TV 241219",
    "duration": 223
  },
  {
    "id": "magnetic-starlight-remix-illit-2024-music-bank-gfj-kbs-world",
    "youtubeId": "HhSTuK6febs",
    "title": "Magnetic (Starlight Remix) - ILLIT 아일릿 [2024 MUSIC BANK GFJ]  KBS WORLD TV 241219",
    "duration": 178
  },
  {
    "id": "illit-dance-break-iykyk-if-you-know-you-know-magnetic-holida",
    "youtubeId": "3pw8UKKKETQ",
    "title": "ILLIT (아일릿) - Dance Break + IYKYK (If You Know You Know) + Magnetic (Holiday Ver.) @가요대전 GayoDaejeon",
    "duration": 230
  },
  {
    "id": "39-illit-intro-cherish-my-love-moonlight-remix-magnetic-jtbc",
    "youtubeId": "pLZMyAbj0io",
    "title": "[제39회 골든디스크] ILLIT - \\",
    "duration": 343
  },
  {
    "id": "almond-chocolate-korean-ver-illit-music-bank-kbs-world-tv-25",
    "youtubeId": "-uQmO9dijRk",
    "title": "Almond Chocolate (Korean Ver.) - ILLIT アイリット 아일릿 [Music Bank] | KBS WORLD TV 250314",
    "duration": 231
  },
  {
    "id": "illit-almond-chocolate-korean-ver-show-musiccore-mbc250315",
    "youtubeId": "kvrKpXMoHeA",
    "title": "ILLIT (아일릿) - Almond Chocolate (Korean Ver.) | Show! MusicCore | MBC250315방송",
    "duration": 218
  },
  {
    "id": "illit-almond-chocolate-korean-ver-inkigayo-20250316",
    "youtubeId": "DiwANBRF8rc",
    "title": "ILLIT (아일릿) - Almond Chocolate (Korean Ver.) @인기가요 inkigayo 20250316",
    "duration": 226
  },
  {
    "id": "almond-chocolate-korean-ver-illit-music-bank-kbs-world-tv-25-DDzxfR",
    "youtubeId": "DDzxfRX1FFE",
    "title": "Almond Chocolate (Korean Ver.) - ILLIT アイリット 아일릿 [Music Bank] | KBS WORLD TV 250321",
    "duration": 212
  },
  {
    "id": "spotify-exclusive-illit-almond-chocolatejapanese-ver-sbs-ink",
    "youtubeId": "vCFqYBtvdXI",
    "title": "[Spotify Exclusive] ILLIT 아일릿 \\",
    "duration": 204
  },
  {
    "id": "illit-intro-cherish-my-love-sbs-250427",
    "youtubeId": "5kTYtNQ4t7k",
    "title": "아일릿(ILLIT) - INTRO + Cherish (My Love) | SBS 250427 방송",
    "duration": 203
  },
  {
    "id": "illit-tick-tackcherishmy-love-2025",
    "youtubeId": "euOdoRgqG8Y",
    "title": "ILLIT - Tick-Tack+Cherish(My love) | 트렌드웨이브 2025",
    "duration": 315
  },
  {
    "id": "illit-almond-chocolate-from-beat-ax-vol6",
    "youtubeId": "Bm3qryDSfno",
    "title": "ILLIT 「Almond Chocolate｣ from 『BEAT AX Vol.6』",
    "duration": 113
  },
  {
    "id": "full-focus-illit-full-ver250522-kudyssey-3",
    "youtubeId": "8T4D5b1Cips",
    "title": "[FULL FOCUS] 고려대학교 축제 아일릿 (ILLIT) Full ver.ㅣ250522 석탑대동제 KUDYSSEY 3일차",
    "duration": 1353
  },
  {
    "id": "illit-magnetic-glitterday-in-seoul",
    "youtubeId": "yuOPNwfvfC4",
    "title": "ILLIT (아일릿) ‘Magnetic’ @GLITTERDAY IN SEOUL",
    "duration": 187
  },
  {
    "id": "-illit-do-the-dance-ep893-mnet-250619",
    "youtubeId": "c4hnTU4L1sc",
    "title": "\\",
    "duration": 250
  },
  {
    "id": "-do-the-dance-illit-music-bank-kbs-250620",
    "youtubeId": "Vm2we452zEs",
    "title": "빌려온 고양이(Do the Dance) - 아일릿 (ILLIT) [뮤직뱅크/Music Bank] | KBS 250620 방송",
    "duration": 215
  },
  {
    "id": "illit-do-the-dance-show-musiccore-mbc250621",
    "youtubeId": "a-SA3qDBMlI",
    "title": "ILLIT (아일릿) - Do the Dance (빌려온 고양이) | Show! MusicCore | MBC250621방송",
    "duration": 230
  },
  {
    "id": "-illit-do-the-dance-sbs-250622",
    "youtubeId": "AwDjYv56H_U",
    "title": "아일릿 (ILLIT) - 빌려온 고양이 (Do the Dance) | SBS 250622 방송",
    "duration": 205
  },
  {
    "id": "-illit-do-the-dance-ep894-mnet-250626",
    "youtubeId": "2V_-Oium7SQ",
    "title": "아일릿 (ILLIT) - 빌려온 고양이 (Do the Dance) #엠카운트다운 EP.894 | Mnet 250626 방송",
    "duration": 199
  },
  {
    "id": "-do-the-dance-illit-music-bank-kbs-250627",
    "youtubeId": "m6PNhsbur1I",
    "title": "빌려온 고양이(Do the Dance) - 아일릿 (ILLIT) [뮤직뱅크/Music Bank] | KBS 250627 방송",
    "duration": 196
  },
  {
    "id": "illit-do-the-dance-show-musiccore-mbc250628",
    "youtubeId": "JdmiGy2jwik",
    "title": "ILLIT (아일릿) - Do the Dance (빌려온 고양이) | Show! MusicCore | MBC250628방송",
    "duration": 195
  },
  {
    "id": "-illit-do-the-dance-sbs-250629",
    "youtubeId": "64EiaePsEj8",
    "title": "아일릿 (ILLIT) - 빌려온 고양이 (Do the Dance) | SBS 250629 방송",
    "duration": 198
  },
  {
    "id": "illit-do-the-dance-myk-festa-myk-live-kpop",
    "youtubeId": "D6EaJTkVsFQ",
    "title": "ILLIT, 빌려온 고양이 (Do the Dance) | MyK FESTA | MyK LIVE KPOP",
    "duration": 190
  },
  {
    "id": "-illit-do-the-dance-ep895-mnet-250703",
    "youtubeId": "PtLSl14VEDg",
    "title": "아일릿 (ILLIT) - 빌려온 고양이 (Do the Dance) #엠카운트다운 EP.895 | Mnet 250703 방송",
    "duration": 213
  },
  {
    "id": "-do-the-dance-illit-music-bank-kbs-250704",
    "youtubeId": "1eKVpV5B_d0",
    "title": "빌려온 고양이(Do the Dance) - 아일릿 (ILLIT) [뮤직뱅크/Music Bank] | KBS 250704 방송",
    "duration": 199
  },
  {
    "id": "-illit-do-the-dance-sbs-250706",
    "youtubeId": "3bg9jfQMUJo",
    "title": "아일릿 (ILLIT) - 빌려온 고양이 (Do the Dance) | SBS 250706 방송",
    "duration": 190
  },
  {
    "id": "illit-tick-tack-myk-festa-myk-live-kpop",
    "youtubeId": "O7ASWzE5kU8",
    "title": "ILLIT, Tick-Tack | MyK FESTA | MyK LIVE KPOP",
    "duration": 131
  },
  {
    "id": "-illit-jellyous-ep896-mnet-250710",
    "youtubeId": "aNIKZKwSjX8",
    "title": "\\",
    "duration": 176
  },
  {
    "id": "illit-jellyous-music-bank-kbs-world-tv-250711",
    "youtubeId": "S9rJFkfoh5Q",
    "title": "ILLIT アイリット 아일릿 - jellyous [Music Bank] | KBS WORLD TV 250711",
    "duration": 189
  },
  {
    "id": "illit-jellyous-show-musiccore-mbc250712",
    "youtubeId": "84IHLjcBpQk",
    "title": "ILLIT (아일릿) - jellyous | Show! MusicCore | MBC250712방송",
    "duration": 169
  },
  {
    "id": "-illit-jellyous-sbs-250713",
    "youtubeId": "nWJgn8iUpCE",
    "title": "아일릿 (ILLIT) - jellyous | SBS 250713 방송",
    "duration": 177
  },
  {
    "id": "-illit-jellyous-ep897-mnet-250717",
    "youtubeId": "qLovrnXpfwI",
    "title": "아일릿 (ILLIT) - jellyous #엠카운트다운 EP.897 | Mnet 250717 방송",
    "duration": 191
  },
  {
    "id": "jellyous-illit-music-bank-kbs-250718",
    "youtubeId": "wKGsPG18IMo",
    "title": "jellyous - 아일릿 (ILLIT) [뮤직뱅크/Music Bank] | KBS 250718 방송",
    "duration": 178
  },
  {
    "id": "illit-jellyous-show-musiccore-mbc250719",
    "youtubeId": "l4aZWXTYX2E",
    "title": "ILLIT (아일릿) - jellyous | Show! MusicCore | MBC250719방송",
    "duration": 169
  },
  {
    "id": "-illit-jellyous-ep898-mnet-250724",
    "youtubeId": "keVsrE81aYU",
    "title": "아일릿 (ILLIT) - jellyous #엠카운트다운 EP.898 | Mnet 250724 방송",
    "duration": 174
  },
  {
    "id": "jellyous-illit-music-bank-kbs-250725",
    "youtubeId": "T-LlE5t-54M",
    "title": "jellyous - 아일릿 (ILLIT) [뮤직뱅크/Music Bank] | KBS 250725 방송",
    "duration": 177
  },
  {
    "id": "illit-jellyous-show-musiccore-mbc250726",
    "youtubeId": "1oZm6EjsVKw",
    "title": "ILLIT (아일릿) - jellyous | Show! MusicCore | MBC250726방송",
    "duration": 169
  },
  {
    "id": "-illit-l-kbs-250803",
    "youtubeId": "pmKt81zmemU",
    "title": "둠칫냐옹 🐱 열린음악회에 찾아온 다섯 고양이 아일릿 🩰 ILLIT 아일릿 \\",
    "duration": 190
  },
  {
    "id": "illit-cherish-my-love-open-concert-ep1534-kbs-korea-250803",
    "youtubeId": "B8LYXRril5E",
    "title": "ILLIT - Cherish (My Love) [Open Concert : EP.1534] | KBS KOREA 250803",
    "duration": 183
  },
  {
    "id": "illit-intro-do-the-dance-summer-ver",
    "youtubeId": "3WVHyhY559E",
    "title": "아일릿(ILLIT) - INTRO + 빌려온 고양이 (Do the Dance) (Summer Ver.)♬",
    "duration": 261
  },
  {
    "id": "illit-jellyous-performance-at-sbs-gayo-daejeon-2025",
    "youtubeId": "Ps2sEQK8kBQ",
    "title": "ILLIT (아일릿) ",
    "duration": 172
  },
  {
    "id": "illit-glitter-day-in-japan-topping-performance-movie",
    "youtubeId": "Rq9ITkQbeeI",
    "title": "ILLIT (아일릿) GLITTER DAY IN JAPAN 「Topping」 Performance Movie",
    "duration": 173
  },
  {
    "id": "250823-illit-live-2025-tmelive-international-music-awards-20",
    "youtubeId": "3N3zlYUSd9g",
    "title": "250823 ILLIT Live - 2025 TMElive International Music Awards (2025 TIMA國際音樂大賞)",
    "duration": 1172
  },
  {
    "id": "illit-magnetic-tmelive-international-music-awards",
    "youtubeId": "MrAB8wiIQ2s",
    "title": "ILLIT (아일릿) ‘Magnetic’ @ TMElive International Music Awards",
    "duration": 164
  },
  {
    "id": "illit-japan-1st-single-release-showcase-performance-movie",
    "youtubeId": "2RF_zggD1Vg",
    "title": "ILLIT (아일릿) Japan 1st Single 「時よ止まれ」 Release Showcase Performance Movie",
    "duration": 204
  },
  {
    "id": "illit-oops-glitter-day-in-japan",
    "youtubeId": "pkGVFzvFibA",
    "title": "ILLIT (아일릿) ‘oops!’ @GLITTER DAY IN JAPAN",
    "duration": 208
  },
  {
    "id": "illit-glitter-day-in-japan-performance-movie",
    "youtubeId": "oUDNUv7D3n8",
    "title": "ILLIT (아일릿) GLITTER DAY IN JAPAN 「時よ止まれ」 Performance Movie",
    "duration": 190
  },
  {
    "id": "illit-full-ver-tick-tack-oops-jellyous-magnetic-250919",
    "youtubeId": "u-nj-gROZNc",
    "title": "아일릿(ILLIT) Full ver. (빌려온 고양이 + Tick-Tack + oops! + jellyous + Magnetic)  직캠 | 성신여대 축제 • 250919",
    "duration": 1453
  },
  {
    "id": "illit-japan-tv-250920",
    "youtubeId": "bxzieNVTNY8",
    "title": "ILLIT JAPAN TV 250920",
    "duration": 172
  },
  {
    "id": "-2025-seoul-international-drama-awards-2025",
    "youtubeId": "TGbS3QZkWW0",
    "title": "서울드라마어워즈 2025 | 아일릿 - 빌려온 고양이 | Seoul International Drama Awards 2025",
    "duration": 186
  },
  {
    "id": "illit-251015-1",
    "youtubeId": "D8p_WEuRwKk",
    "title": "[ILLIT] 251015 아일릿 1열 뷰 🧲",
    "duration": 547
  },
  {
    "id": "illit-oops-rock-in-japan-festival-2025",
    "youtubeId": "VBM_6h8nB4g",
    "title": "ILLIT (아일릿) ‘oops!’ @ROCK IN JAPAN FESTIVAL 2025",
    "duration": 256
  },
  {
    "id": "illit-perfect-night-glitterday-encore",
    "youtubeId": "aFNxGemp8LM",
    "title": "ILLIT (아일릿) ‘Perfect Night’ @GLITTERDAY ENCORE",
    "duration": 125
  },
  {
    "id": "illit-lucky-girl-syndrome-glitterday-encore",
    "youtubeId": "20h6kR-NpaQ",
    "title": "ILLIT (아일릿) ‘Lucky Girl Syndrome’ @GLITTERDAY ENCORE",
    "duration": 146
  },
  {
    "id": "comeback-illit-not-cute-anymore-music-bank-kbs-world-tv-2511",
    "youtubeId": "amn6SDCrFWs",
    "title": "[COMEBACK🎉] ILLIT アイルリット 아일릿 - NOT CUTE ANYMORE [Music Bank] | KBS WORLD TV 251128",
    "duration": 203
  },
  {
    "id": "illit-not-cute-anymore-show-musiccore-mbc251129",
    "youtubeId": "e3lNgasgfEA",
    "title": "ILLIT (아일릿) - NOT CUTE ANYMORE | Show! MusicCore | MBC251129방송",
    "duration": 152
  },
  {
    "id": "not-cute-anymore-illit-sbs-251130",
    "youtubeId": "HvQgzMZ3yCs",
    "title": "NOT CUTE ANYMORE - ILLIT | SBS 251130 방송",
    "duration": 154
  },
  {
    "id": "illit-not-cute-anymore-music-bank-kbs-world-tv-251205",
    "youtubeId": "m__-X4hU3oE",
    "title": "ILLIT アイルリット 아일릿 - NOT CUTE ANYMORE [Music Bank] | KBS WORLD TV 251205",
    "duration": 166
  },
  {
    "id": "sub-with-illlit",
    "youtubeId": "o1SDjxBZjOA",
    "title": "[SUB] 전교생 앞에서 아일릿 영업하는데 아일릿이 나타났다 | [딩고어택] 학교편 with 아일릿 (ILLLIT)",
    "duration": 1387
  },
  {
    "id": "illit-not-cute-anymore-show-musiccore-mbc251206",
    "youtubeId": "C60Eteco8kg",
    "title": "ILLIT (아일릿) - NOT CUTE ANYMORE | Show! MusicCore | MBC251206방송",
    "duration": 142
  },
  {
    "id": "not-cute-anymore-illit-sbs-251207",
    "youtubeId": "FzqSsg4nVKc",
    "title": "NOT CUTE ANYMORE - ILLIT | SBS 251207 방송",
    "duration": 154
  },
  {
    "id": "illit-oops-spotify-performance-video",
    "youtubeId": "wpokz1JhGl0",
    "title": "ILLIT (아일릿) ‘oops!’ @ Spotify Performance Video",
    "duration": 201
  },
  {
    "id": "illit-not-cute-anymore-show-musiccore-mbc251213",
    "youtubeId": "N0hBFhHqjhs",
    "title": "ILLIT (아일릿) - NOT CUTE ANYMORE | Show! MusicCore | MBC251213방송",
    "duration": 142
  },
  {
    "id": "jellyous-10cm-x-illit-2025-kbs-251219",
    "youtubeId": "jIHSvI2y500",
    "title": "jellyous + 너에게 닿기를 - 10CM X 민주 (ILLIT) [2025 가요대축제 글로벌 페스티벌] | KBS 251219 방송",
    "duration": 251
  },
  {
    "id": "mma2025-illit-not-cute-anymore-4k-illit-20251220",
    "youtubeId": "mYdCaqWrwpA",
    "title": "[#MMA2025] ILLIT - 빌려온 고양이 + Not Cute Anymore (4K) | #ILLIT #아일릿 #20251220",
    "duration": 450
  },
  {
    "id": "woonhak-x-wonhee-x-sbs-gayodaejeon",
    "youtubeId": "8fmiu1YvLt8",
    "title": "WOONHAK X WONHEE(눈사람즈 운학 X 원희) - 미리 메리 크리스마스 (원곡: 아이유) @SBS GayoDaejeon",
    "duration": 170
  },
  {
    "id": "illit-intro-dance-break-not-cute-anymore-ver-jellyous-sbs-ga",
    "youtubeId": "MGmtQUIgUhY",
    "title": "ILLIT(아일릿) - INTRO DANCE BREAK + NOT CUTE ANYMORE (가요대전 Ver.) + jellyous @SBS GayoDaejeon",
    "duration": 244
  },
  {
    "id": "illit-almond-chocolate-glitterday-in-japan",
    "youtubeId": "U01Ldel-mG4",
    "title": "ILLIT (아일릿) ‘ Almond Chocolate’ @GLITTERDAY IN JAPAN",
    "duration": 230
  },
  {
    "id": "intro-jellyous-not-cute-anymoree-illit-2025-in-japan-kbs-251",
    "youtubeId": "wZ_agYXOXsI",
    "title": "INTRO + jellyous + NOT CUTE ANYMOREE - 아일릿 (ILLIT) [2025 뮤직뱅크 글로벌페스티벌 IN JAPAN] | KBS 251230 방송",
    "duration": 286
  },
  {
    "id": "2025-mbc-illit-not-cute-anymore-do-the-dance-mbc-251231",
    "youtubeId": "ob1nefArGv4",
    "title": "[2025 MBC 가요대제전] ILLIT (아일릿) -  NOT CUTE ANYMORE + Do the Dance (빌려온 고양이), MBC 251231 방송",
    "duration": 244
  },
  {
    "id": "2025-mbc-ian-bang-jeemin-wonhee-up-mbc-251231",
    "youtubeId": "yiVnKyvhNwk",
    "title": "[2025 MBC 가요대제전] IAN & BANG JEEMIN & WONHEE (이.방.원) - UP & 첫 사랑니 & 좋은 날, MBC 251231 방송",
    "duration": 287
  },
  {
    "id": "2025-mbc-illit-secret-quest-mbc-251231",
    "youtubeId": "6MhQ3_NLVJM",
    "title": "[2025 MBC 가요대제전] ILLIT (아일릿) - Secret Quest (비밀찾기), MBC 251231 방송",
    "duration": 218
  },
  {
    "id": "-illit-not-cute-anymore-ep911-mnet-260108",
    "youtubeId": "tnckXKaPxkE",
    "title": "아일릿 (ILLIT) - NOT CUTE ANYMORE #엠카운트다운 EP.911 | Mnet 260108 방송",
    "duration": 158
  },
  {
    "id": "not-cute-anymore-illit-sbs-260111",
    "youtubeId": "beqXjbITAAE",
    "title": "NOT CUTE ANYMORE - 아일릿 (ILLIT) | SBS 260111 방송",
    "duration": 148
  },
  {
    "id": "illit-magnetic-dance-practice-fix-ver",
    "youtubeId": "6KIuzXYR16Y",
    "title": "ILLIT (아일릿) ‘Magnetic’ Dance Practice (Fix Ver.)",
    "duration": 167
  },
  {
    "id": "illit-magnetic-dance-practice-moving-ver",
    "youtubeId": "hCg9tezGBWE",
    "title": "ILLIT (아일릿) ‘Magnetic’ Dance Practice (Moving Ver.)",
    "duration": 170
  },
  {
    "id": "illit-lucky-girl-syndrome-dance-practice",
    "youtubeId": "HZDru95g6Mg",
    "title": "ILLIT (아일릿) ‘Lucky Girl Syndrome’ Dance Practice",
    "duration": 155
  },
  {
    "id": "illit-kcon-japan-2024-what-is-love-dance-practice-twice",
    "youtubeId": "EjPlBHdVH70",
    "title": "ILLIT (아일릿) KCON JAPAN 2024 ‘What is Love?’ Dance Practice (원곡: TWICE)",
    "duration": 162
  },
  {
    "id": "illit-2024-sbs-summer-dance-practice-tws",
    "youtubeId": "pII49xbzGdU",
    "title": "ILLIT (아일릿) 2024 SBS 가요대전 Summer ‘첫 만남은 계획대로 되지 않아’ Dance Practice (원곡: TWS)",
    "duration": 117
  },
  {
    "id": "illit-cherish-my-love-dance-practice-moving-ver",
    "youtubeId": "fNrvVVjzZ4M",
    "title": "ILLIT (아일릿) ‘Cherish (My Love)’ Dance Practice (Moving Ver.)",
    "duration": 183
  },
  {
    "id": "illit-cherish-my-love-dance-practice-fix-ver",
    "youtubeId": "bD9aJN48kuE",
    "title": "ILLIT (아일릿) ‘Cherish (My Love)’ Dance Practice (Fix Ver.)",
    "duration": 182
  },
  {
    "id": "illit-tick-tack-dance-practice",
    "youtubeId": "HdmcYh1r7Q4",
    "title": "ILLIT (아일릿) ‘Tick-Tack’ Dance Practice",
    "duration": 152
  },
  {
    "id": "illit-2024-mama-awards-magnetic-cherish-my-love-dance-practi",
    "youtubeId": "9trHCv1WP7c",
    "title": "ILLIT (아일릿) 2024 MAMA AWARDS ‘Magnetic & Cherish (My Love)’ Dance Practice",
    "duration": 462
  },
  {
    "id": "illit-2024-in-japan-tick-tack-dance-practice",
    "youtubeId": "ymWZ5Tevleg",
    "title": "ILLIT (아일릿) 2024 뮤직뱅크 글로벌 페스티벌 in JAPAN ‘Tick-Tack’ Dance Practice",
    "duration": 239
  },
  {
    "id": "illit-2024-sbs-iykyk-if-you-know-you-know-dance-practice",
    "youtubeId": "FNlQepA-WZE",
    "title": "ILLIT (아일릿) 2024 SBS 가요대전 ‘IYKYK (If You Know You Know)’ Dance Practice",
    "duration": 125
  },
  {
    "id": "illit-39-intro-cherish-my-love-moonlight-remix-dance-practic",
    "youtubeId": "HnKx9S8EJa0",
    "title": "ILLIT (아일릿) 제39회 골든디스크어워즈 ‘Intro & Cherish (My Love) (Moonlight Remix)’ Dance Practice",
    "duration": 232
  },
  {
    "id": "illit-do-the-dance-dance-practice",
    "youtubeId": "htXv7fpQlNc",
    "title": "ILLIT (아일릿) \\",
    "duration": 199
  },
  {
    "id": "illit-jellyous-dance-practice",
    "youtubeId": "E5joqiTD0ws",
    "title": "ILLIT (아일릿) ‘jellyous’ Dance Practice",
    "duration": 172
  },
  {
    "id": "illit-not-cute-anymore-dance-practice",
    "youtubeId": "-tgJECVba9c",
    "title": "ILLIT (아일릿) ‘NOT CUTE ANYMORE’ Dance Practice",
    "duration": 145
  },
  {
    "id": "illit-mma2025-dance-practice",
    "youtubeId": "fyJJm2vLfH0",
    "title": "ILLIT (아일릿) MMA2025 Dance Practice",
    "duration": 452
  },
  {
    "id": "illit-2025-sbs-dance-practice",
    "youtubeId": "eVzVWS2BCek",
    "title": "ILLIT (아일릿) 2025 SBS 가요대전 Dance Practice",
    "duration": 110
  },
  {
    "id": "illit-super-illit-ep1-part1",
    "youtubeId": "BUUHUS4e1ZM",
    "title": "ILLIT (아일릿) \\",
    "duration": 1418
  },
  {
    "id": "illit-super-illit-ep2-part2",
    "youtubeId": "7ZBUmEedKdw",
    "title": "ILLIT (아일릿) \\",
    "duration": 1366
  },
  {
    "id": "-illit-super-illit-ep12",
    "youtubeId": "1wz_UGti6bk",
    "title": "첫 자컨 촬영에 신난 아일릿 | 이렇게 귀여우면 우주최강 예능짱 밖에 못 돼 | ILLIT (아일릿) ‘SUPER ILLIT’ EP.1~2 비하인드",
    "duration": 523
  },
  {
    "id": "illit-super-illit-ep3",
    "youtubeId": "8USY9Mhi8Ro",
    "title": "ILLIT (아일릿) \\",
    "duration": 1399
  },
  {
    "id": "illit-super-illit-ep4",
    "youtubeId": "syYTEF3Tojs",
    "title": "ILLIT (아일릿) \\",
    "duration": 1445
  },
  {
    "id": "-illit-super-illit-ep34",
    "youtubeId": "o9TKuiZd6bU",
    "title": "완벽한 날씨에 피크닉 다녀옴☀️ | 아일릿 컴퍼니면 주말 출근도 가능💼 | ILLIT (아일릿) ‘SUPER ILLIT’ EP.3~4 비하인드",
    "duration": 590
  },
  {
    "id": "illit-super-illit-ep5-feat",
    "youtubeId": "IJNGnKBQj6c",
    "title": "ILLIT (아일릿) \\",
    "duration": 1778
  },
  {
    "id": "illit-super-illit-ep6-who-is-the-killer",
    "youtubeId": "L5vhVjNLQq8",
    "title": "ILLIT (아일릿) \\",
    "duration": 2152
  },
  {
    "id": "-max-illit-super-illit-ep56",
    "youtubeId": "FmLYGDqBICw",
    "title": "추리 게임 과몰입🕵🏻 | 붕방력 MAX 물 속성 아일릿💦 | ILLIT (아일릿) ‘SUPER ILLIT’ EP.5~6 비하인드",
    "duration": 496
  },
  {
    "id": "illit-super-illit-ep7-welcome",
    "youtubeId": "hgTB_r2sfKE",
    "title": "ILLIT (아일릿) \\",
    "duration": 1288
  },
  {
    "id": "illit-super-illit-ep8",
    "youtubeId": "KNULtWMWDuw",
    "title": "ILLIT (아일릿) \\",
    "duration": 1797
  },
  {
    "id": "-illit-super-illit-ep78",
    "youtubeId": "2LY2XTzj6-E",
    "title": "현실 공주님들 등장~👑 (현타 주의) | 아일릿 왕국의 숨겨진 뒷 이야기 | ILLIT (아일릿) ‘SUPER ILLIT’ EP.7~8 비하인드",
    "duration": 314
  },
  {
    "id": "illit-super-illit-ep9",
    "youtubeId": "V6STrcCes6Y",
    "title": "ILLIT (아일릿) \\",
    "duration": 1568
  },
  {
    "id": "illit-super-illit-ep10",
    "youtubeId": "xcsPOE8dGBE",
    "title": "ILLIT (아일릿) \\",
    "duration": 1700
  },
  {
    "id": "-illit-super-illit-ep910",
    "youtubeId": "9jG56D_3aXM",
    "title": "(스포주의) 무서운 게 딱 좋아! 의외로 공포를 즐김 | 귀신한테도 팬서비스하는 프로 아이돌🫶 | ILLIT (아일릿) ‘SUPER ILLIT’ EP.9~10 비하인드",
    "duration": 453
  },
  {
    "id": "-illit-super-illit-ep11",
    "youtubeId": "Ppx_KChr3vU",
    "title": "얼어 죽어도 아일릿 ▶ ILLIT (아일릿) \\",
    "duration": 1752
  },
  {
    "id": "-illit-super-illit-ep12-9ljdyB",
    "youtubeId": "9ljdyBAFHN8",
    "title": "아일릿 내가 낳을걸...! ▶ ILLIT (아일릿) \\",
    "duration": 2197
  },
  {
    "id": "-5-max-illit-super-illit-ep1112",
    "youtubeId": "sVm4fn_S5g8",
    "title": "눈물의 어워드💦 그 후 | 5살로 돌아간 멤버들🖐️ | 동계 스포츠 도전! 장꾸력 MAX 뒷이야기ㅋㅋ | ILLIT (아일릿) ‘SUPER ILLIT’ EP.11~12 비하인드",
    "duration": 660
  },
  {
    "id": "-illit-super-illit-ep13",
    "youtubeId": "0PFollSkbCQ",
    "title": "안녕히 계세용 언니들 ^^~♥ ▶ ILLIT (아일릿) \\",
    "duration": 1471
  },
  {
    "id": "-illit-super-illit-ep14",
    "youtubeId": "5rXNVYJs4zk",
    "title": "릿그 오브 레전드 ▶ ILLIT (아일릿) \\",
    "duration": 1793
  },
  {
    "id": "pc-illit-super-illit-ep1314",
    "youtubeId": "6DBAJQLZq9I",
    "title": "PC방에 롤 여신 교복릿의 등장이라🌟 | 홍대를 누비는 언니즈&동생즈 | ILLIT (아일릿) ‘SUPER ILLIT’ EP.13~14 비하인드",
    "duration": 493
  },
  {
    "id": "-illit-super-illit-ep15",
    "youtubeId": "ouWGOxGr0RE",
    "title": "글릿이 보고 싶으면 방송을 만들면 됩니다 ▶ ILLIT (아일릿) \\",
    "duration": 1771
  },
  {
    "id": "-illit-super-illit-ep16",
    "youtubeId": "fheoRMGo_Ms",
    "title": "막 내가 좋아? ▶ ILLIT (아일릿) \\",
    "duration": 1554
  },
  {
    "id": "-dj-illit-super-illit-ep1516",
    "youtubeId": "sc7F9NUvEuc",
    "title": "라디오 DJ 데뷔기 | 흑화 아일릿의 우당탕탕 스파이 검거🕵️ | 아초파 보스 이로하 깜짝 생파🎂 | ILLIT (아일릿) ‘SUPER ILLIT’ EP.15~16 비하인드",
    "duration": 593
  },
  {
    "id": "-illit-super-illit-ep17",
    "youtubeId": "WQQx5lTDYWY",
    "title": "호랑님도 두 손 두 발 들었지 ▶ ILLIT (아일릿) \\",
    "duration": 1934
  },
  {
    "id": "-illit-super-illit-ep18",
    "youtubeId": "g7D3h-1hC8s",
    "title": "아일릿을 속였습니다 ▶ ILLIT (아일릿) \\",
    "duration": 2022
  },
  {
    "id": "-illit-super-illit-ep18-feBTQ_",
    "youtubeId": "feBTQ_7JF7s",
    "title": "미공개 깜짝 카메라 ▶ ILLIT (아일릿) \\",
    "duration": 432
  },
  {
    "id": "-zip-illit-super-illit-ep1718",
    "youtubeId": "Y-MNwAsf-Dg",
    "title": "떡집 소녀들 상황극 남발 비하인드 | 깜짝 카메라.zip | 다음 슈일릿 희망 사항은요…! | ILLIT (아일릿) ‘SUPER ILLIT’ EP.17~18 비하인드",
    "duration": 440
  },
  {
    "id": "-illit-super-illit",
    "youtubeId": "E9ryugPZ9yM",
    "title": "막장 어린이 드라마 ▶ ILLIT (아일릿) \\",
    "duration": 187
  },
  {
    "id": "x-1-l-l-7-19-l-illit",
    "youtubeId": "b30wGhRlDkc",
    "title": "윤아X원희의 웰빙라이프 도전기 제 1장 💪계단 오르기 l 수직 마라톤 l 지하 7층부터 19층까지 걸어 올라가기 l ILLIT (아일릿) [느려도 좋아]",
    "duration": 933
  },
  {
    "id": "x-2-l-l-l-illit",
    "youtubeId": "YV1bVUCtQ1A",
    "title": "윤아X원희의 웰빙라이프 도전기 제 2장 💪가속 노화 멈춰! l 양배추 한 통 털기 l 느리게 씹기의 효능 l ILLIT (아일릿) [느려도 좋아]",
    "duration": 892
  },
  {
    "id": "-l-l-l-l-illit",
    "youtubeId": "hGFgzu71aco",
    "title": "윤아 도령과 원희 도령의 마음 다스리기 l 서예 체험 l 심박수 제한 미션 (벌칙: 두리안 먹기) l 전격 프로그램 하차 선언⁉️ l ILLIT (아일릿) [느려도 좋아]",
    "duration": 1095
  },
  {
    "id": "illit-ep1",
    "youtubeId": "SKYtnn2DCYA",
    "title": "ILLIT(아일릿) \\",
    "duration": 904
  },
  {
    "id": "illit-ep2",
    "youtubeId": "4UeTS-v5ZaU",
    "title": "ILLIT(아일릿) \\",
    "duration": 954
  },
  {
    "id": "illit",
    "youtubeId": "BV_McypmJ_Y",
    "title": "ILLIT(아일릿) \\",
    "duration": 1291
  },
  {
    "id": "-illit-holo-ep1",
    "youtubeId": "Gw30iYhWLZw",
    "title": "📢과몰입 주의보 발령! 🤯 ",
    "duration": 1912
  },
  {
    "id": "holo-2-illit-holo-ep2",
    "youtubeId": "xwovSt1n3Hc",
    "title": "HOLO 나라, 너무 빨라서 더 뜨겁다🔥 2화 만에 최종 선택! 과연 그녀들의 선택은?! ▶︎ ILLIT(아일릿) \\",
    "duration": 2770
  },
  {
    "id": "-l-l-l-illit",
    "youtubeId": "khvW8JfzDjw",
    "title": "느리게 생각하기의 효능💡 l 수상한(?) 건강 체조👏 l 멍 때리기를 빙자한 웃참 미션 ㅋㅋ l ILLIT (아일릿) [느려도 좋아]",
    "duration": 994
  },
  {
    "id": "-l-l-l-illit-AnK5bU",
    "youtubeId": "AnK5bUXQ0ac",
    "title": "다섯 아씨 자매의 우당탕탕 비밀 미션💌 l 추석 맞이🍂 할머니 배 집안일 대결 l 과몰입 주의 l ILLIT (아일릿) [아씨 자매전]",
    "duration": 968
  },
  {
    "id": "eng-2-ep15",
    "youtubeId": "YewJ5eo4gDc",
    "title": "[ENG] 아일릿 너 왜 안 귀여운 척 하는거야? / 밥사효2 EP.15 아일릿 편",
    "duration": 1843
  },
  {
    "id": "sub-ep53-1-illit-not-cute-zone-1-4k",
    "youtubeId": "ykbnR7-ki7I",
    "title": "[SUB] EP.53-1 ILLIT | 우리 진짜 안 귀엽다고💥 돌박 한정판 랜플댄 ❤️‍🔥 아일릿, 파리에 가다 | 돌박이일 아일릿 NOT CUTE ZONE 투어 1탄 [4K]",
    "duration": 2376
  },
  {
    "id": "-not-cute-anymore-not-cute-anymore-1-illit-play-it",
    "youtubeId": "K-jgTQxJLMg",
    "title": "[𝐏𝐥𝐚𝐲𝐥𝐢𝐬𝐭] 직장 스트레스엔 NOT CUTE ANYMORE 듣기🎧 | NOT CUTE ANYMORE 1시간 반복 재생 | ILLIT (아일릿) [PLAY-IT]",
    "duration": 3656
  },
  {
    "id": "sub-ep53-2-illit-not-cute-zone-2-4k",
    "youtubeId": "lt8MAeW26qE",
    "title": "[SUB] EP.53-2 ILLIT | 아일릿 ○○, 퇴근 후 날아다닌다고? 상황극의 달인은 당황하지 않지🤫 | 돌박이일 아일릿 NOT CUTE ZONE 투어 2탄 [4K]",
    "duration": 3403
  },
  {
    "id": "-i",
    "youtubeId": "_FHFLdf4IeE",
    "title": "저희끼리 떠들다 보니 여기까지 왔습니다 I 선공개 #슈일릿",
    "duration": 286
  },
  {
    "id": "-i-ikNZGs",
    "youtubeId": "ikNZGsVRcuk",
    "title": "재밌는 슈퍼아일릿이 될 거야 I 티저 #슈일릿",
    "duration": 113
  },
  {
    "id": "-9-i-ep19",
    "youtubeId": "65RgEY46kWo",
    "title": "주어진 시간은 단 9시간! 갑니다 모카의 고향 후쿠오카로..!✈️ 아일릿 데리고 후쿠오카 당일치기 가능? I #슈퍼아일릿 #EP19",
    "duration": 2067
  },
  {
    "id": "-9-i-i-ep20",
    "youtubeId": "PJTajEDU-O4",
    "title": "주어진 시간은 단 9시간! 갑니다 모카의 고향 후쿠오카로..!✈️ I 아일릿은 돈키호테에서 뭐삼? 그렇게 거지가 되💸I #슈퍼아일릿 #EP20",
    "duration": 2075
  }
];
